#!/usr/bin/env perl
use strict;
use warnings;
use feature 'say';
use Cwd;
use List::MoreUtils qw/uniq/;
my $cwd = getcwd;

=head1 NAME

show_current_branch - Show the current branch for a set of git repos

=cut

=head1 SYNOPSIS

Run this script from the directory which has all of your SGN repos. By default, it will show you the branch that each SGN repo is on. If you give any command line arguments to the script, it will show you the branch those repos are on.

=head1 EXAMPLES

 $ cd ~/cxgn; show_current_branch

 $ cd ~/git; show_current_branch *

=cut

my @repos = ( qw/sgn cxgn-corelibs ITAG ITAG-analyses tomato_genome
               Phenome Cview perlcyc javacyc SMMID gff3_validator
               biosource sgn-home sgn-devtools art ITAG1_release/, @ARGV);

for my $repo (uniq @repos) {
    chdir $repo if -e $repo;
    next unless -e '.git';
    chomp( my $branch = qx{ git rev-parse --symbolic-full-name HEAD } );
    $branch =~ s!refs/heads/!!;
    say sprintf "%20s\t%20s", $repo,  $branch;
    chdir $cwd;
}
