#!/bin/sh

git clone git@github.com:solgenomics/sgn.git
git clone git@github.com:solgenomics/cxgn-corelibs.git
git clone git@github.com:solgenomics/ITAG.git
git clone git@github.com:solgenomics/Phenome.git
git clone git@github.com:solgenomics/tomato_genome.git
git clone git@github.com:solgenomics/Cview.git
git clone git@github.com:solgenomics/yapri.git
git clone git@github.com:solgenomics/sgn-devtools.git
git clone git@github.com:solgenomics/sgn-biotools.git
git clone git@github.com:solgenomics/sgn-home.git
git clone git@github.com:solgenomics/biosource.git
git clone git@github.com:solgenomics/bio-gff3.git
git clone git@github.com:solgenomics/art.git
git clone git@github.com:solgenomics/perlcyc.git
git clone git@github.com:solgenomics/javacyc.git
git clone git@github.com:solgenomics/SMMID.git
git clone git@github.com:solgenomics/bio-chado-schema.git
git clone git@github.com:solgenomics/bio-chado-loader.git
git clone git@github.com:solgenomics/gff3_validator.git
git clone git@github.com:solgenomics/Ambikon.git
git clone git@github.com:solgenomics/Ambikon-IntegrationServer.git
git clone git@github.com:solgenomics/catalyst-view-bio-seqio.git
