#!/bin/sh

git clone git://github.com/solgenomics/sgn.git
git clone git://github.com/solgenomics/cxgn-corelibs.git
git clone git://github.com/solgenomics/ITAG.git
git clone git://github.com/solgenomics/Phenome.git
git clone git://github.com/solgenomics/tomato_genome.git
git clone git://github.com/solgenomics/Cview.git
git clone git://github.com/solgenomics/sgn-devtools.git
git clone git://github.com/solgenomics/sgn-biotools.git
git clone git://github.com/solgenomics/sgn-home.git
git clone git://github.com/solgenomics/biosource.git
